#!/bin/bash
#
# # crontab -e
# 0 4 * * 1 <path-to-script>
#
# sans script :
# 0 4 * * 1 apt-get -y update >> /var/log/update_script.log && apt-get -y upgrade >> /var/log/update_script.log
#
apt-get -y update >> /var/log/update_script.log
apt-get -y upgrade >> /var/log/update_script.log
